spring.application.name=spring-test
spring.datasource.url=jdbc:postgresql://ep-solitary-frog-a52y51o7-pooler.us-east-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_QU6xRmntp3Eh&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev
#spring.security.user.name=1
#spring.security.user.password=1
#===============JWT=======================
jwt.secret=xyCAV9mHAMRLvpa/I2CfJhDyWjhv04FMtTugyL/cXJw=
jwt.issuer=mohit-mehra
jwt.expiry=900